In [4]:
# Q1
import numpy as np

num = np.arange(2,51)*3
num

array([  6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,  42,
        45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,
        84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117, 120,
       123, 126, 129, 132, 135, 138, 141, 144, 147, 150])

In [11]:
# Q2
l1 = []
l2 = []
for i in range(5):
    l1.append(int(input()))
    l2.append(int(input()))
arr = np.array(l1)
arr1 = np.array(l2)
s = arr+arr1
np.sort(s)

1
5
2
3
5
63
2
45
76
8


array([ 5,  6, 47, 68, 84])

In [16]:
# Q3
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr.ndim)
print(arr.shape)
print(arr.size)

2
(3, 3)
9


In [21]:
# Q4
arr = np.array([1,2,3,4,5,6,67,7,8,9])
print(arr)
print(arr.ndim)
print()
arr1 = np.reshape(arr,(5,2))
print(arr1)
print(arr1.ndim)

[ 1  2  3  4  5  6 67  7  8  9]
1

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [67  7]
 [ 8  9]]
2


In [32]:
# Q5
arr = np.array([1,2,3,4])
arr1 = np.array([5,6,7,8])
arr = np.square(arr)
arr1 = np.square(arr1)
print("arr ",arr)
print("arr1 ",arr1)
print()
print(np.vstack((arr,arr1)))
print()
print(np.hstack((arr,arr1)))


arr  [ 1  4  9 16]
arr1  [25 36 49 64]

[[ 1  4  9 16]
 [25 36 49 64]]

[ 1  4  9 16 25 36 49 64]
